GET http://localhost:4000/users

###
POST http://localhost:4000/registeruser
Content-Type: application/json

{
    "name" : "Joseph",
    "username" : "theman",
    "password" : "password82"
}
###
GET http://localhost:4000/loginuser
Content-Type: application/json

{
    "username" : "a",
    "password" : "password82"

}